### PR TITLE
Allow inclusion in iframe

### PR DESCRIPTION
**Pull request by jwkaltz**

### CODE REVIEW

**Review by ger-benjamin — COMMENTED** [review]
What's the final aim ? Perhaps we could be a little bit more restrictive ?

**Comment by jwkaltz** [comment]
> What's the final aim ? Perhaps we could be a little bit more restrictive ?

The aim is to be able to include the demo GMF in an iframe. I need this for a couple of demos. 
Currently, when trying to do that you get a browser error like "To protect your security, geomapfish-demo-2-5.camptocamp.com will not allow Firefox to display the page if another site has embedded it. To see this page, you need to open it in a new window."

**Review by ger-benjamin — COMMENTED** [review]
For me it's okay but I would like a second opinion

**Review by ger-benjamin — APPROVED** [review]
Okay, so after discussion with @fredj we could add `X-Frame-Options: SAMEORIGIN`
 (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) if you aim is to display the GMF from the same url. Otherwise, don't add it. It's for the demo, so, I think that's okay...

**Comment by arnaud-morvan** [comment]
I've proposed an alternative : #190
Where I just remove the header X-Frame-Options where it is set in CONST_vars.yaml, in index pages (interfaces).

**Pull request merged**
