### PR TITLE
Add Andrea Borghi and Renata Mueller keys

### PR DESCRIPTION
**Pull request by jwkaltz**
add Andrea Borghi and Renata Mueller keys, and change to long key usage, where possible

### CODE REVIEW

**Comment by jwkaltz** [comment]
@sbrunner @danduk82 I see that @ismailsunni 's GPG key was added yesterday, but the secrets.tar.bz2 file not changed (https://github.com/camptocamp/demo_geomapfish/commit/90436e6d4728c4c0ea019e4e0c24a51d6e66de72) - shouldn't the secrets.tar.bz2 file be changed too?

In fact, within this PR, I tried to recreate the secrets.tar.bz2 file as well, but it fails because Ismail's key A90D3D812D4FA142 is not on the gpg server (it seems).
Does it work for you?

**Comment by sbrunner** [comment]
@jwkaltz You should have a secound look because it's the case :-)

**Comment by jwkaltz** [comment]
> @jwkaltz You should have a secound look because it's the case :-)

Ah indeed sorry @sbrunner . But anyway regarding regenerating the file, how did you do it? Do you have a copy of the key? Because I can not get it from the keyserver (the A90D3D812D4FA142 key).

**Comment by sbrunner** [comment]
=> 
```
-----BEGIN PGP PUBLIC KEY BLOCK-----

mQINBF6PF4kBEAC2Gkskm2x+jPLIfIC5EH0tE7l9VOgjjdEuTBg0UgM0VJqgeM62
0BFSKfuLcvblBh1KML9Sy7XNpXarve4Q+Jb7qwdlHUasmKXJ+4Qghm7LTx7lnq2p
HUzFPLatraRkwJqFD5HFIZB+V3cb9lopsTmukt3/Uo35Nj2wgl5NMlyLSqFRSZ4M
vCtcAVKPhEhiG3uXxnKts+RD1RxqphRDh1iVRMnTjy8QTydYKtG3G8xDZr1jYWVe
ydtDGDmtg8W3dBguhJcqhthQwVz/Wns+n8G4oT9mA/tRE+N2wWLVKNAo8p7+1gcL
B4odUMDCzTCqbwJ4llz2N+43If7rqfi9yjkr/WVjTDLYt2CWMTyku3BLEFVw2g59
BCbSWlNf1K2sYMKZAERPaUD2TEW700fU6PJGjPFR5PhleA3S81B/DvLsRXrMcNLR
ziiNhQgiWvt8fcO+UfGWUqspbcohB7dGlg/POHhzhwMI4cPspq0+NYjsfgzoesWz
FiPCksQ5JbwcfOWbMhxCjN5vXDea+mmclC4EKD2Jyt0w1Gxaa88yNl8U9BohiNB4
g6Ge+og+qcscXWWpy8Tbwc817aM2nJ9OB2N449JGmy1wL4FmvJJkprU7iertL4DX
AriaXF+q6jvSJwbJh7/uVC+PDFF1O1nXIkp4ktNCixyXfpKETggbZLDbtQARAQAB
tEtJc21haWwgU3VubmkgKEFub3RoZXIgR1BHIGtleSBpbiBDb3JvbmEgc2l0dWF0
aW9uLikgPGltYWppbWF0aWthQGdtYWlsLmNvbT6JAk4EEwEKADgWIQSgRWAFLeCn
l8fupVGpDT2BLU+hQgUCXo8XiQIbAwULCQgHAgYVCgkICwIEFgIDAQIeAQIXgAAK
CRCpDT2BLU+hQkd3D/9sMreoyFn2IqSThB49VNkIMM2pdoGkvxNUz1UrhPwrhIdK
OkaC4qrjwikHYnKYn4+Vywbwfh+gJJZ8komunQT8PtysuNiG353ipEnCd9G2JbBr
gKHCRhuEV9lqVfAq/cydZQ3B3Pzcv41ZxxwCCgEtbmt++NJOSnDnme8PKmln1YQk
j78IZSNnK9se5QDl3Z0Qcc5enLZXIyknqvJUt6UfKkKoIwkK3LP9C1UbpGuiDo9I
Fy9XprKwRDb0MHiEDaX4l7lIOdyfcrY4/ZRlwhhWvq/y3TlWp2gLxQd2cbwoNfa4
ZwRgDA1fesbwAAl0MbSgHWQWJl7uXEF3GS9IQanIMaDzb6w4bbDAhCe4BYvhq7ca
E8dTMZeTHfYO7WIuY+dJxND+QbUDhRxIvo+qvSoUwxwX5CMijyyjd5YsDPWOxAqa
fqq4i1Q8BflvfB9SNLnNDDxlnsduIfZUb179Ko7UF3OeiQri3jIIxF1P5NffiSHy
Z/dirclnWlw67JCoGEw7m7xRbjPevdekSVt2Fi1H/YgT3aujeSWQmMgF2cGaWyjJ
VRddgKvwt324rr2XPTFfhhavYHw04HvdlG3SweAK0NrXgx3pDB8iQJxJH+uTavFu
TCsR8H2V1qaglNC/mD3Dr0zhnkeJ72bnMkfT3OVB20HqdyCaZMenmu4vjc6Y47kC
DQRejxeJARAAtDARItNqWUqXwY4jzffnIvdoVKS+NIAqFFzvDk0csXAzOmLkfV3t
Nh81KSLYXYhK5llJ/lrpTeD67TNLJcM9oPlxPKfBqT8hZVZVUin42BmxuLdBUv7L
MCDMyUrBJAysFTTzUhxthFp53cbE4Mj1tES8U4yvKX9IoTC0WsJeRMbhtaBdyXW2
NC2TIqAlz814OgRVBo16S5/duq8PW5NxOyoactt48vq5+9qMBHH7pCFHXDR/CT5y
7Q40gZNqtkboBe7KaEX7aWbpGGRCxXNh5HQjR9vAjb+u3kKooay52hbaFifCUr97
DtwMjQds89j3q/TX6G+W/OYbTelJAcc9Y0SSgbRe77eMek9svF3Uzn2gBgkQJ1Rn
yEDU/FwQEK5rG4UWTEPn3Z2pnm8ZkXZhQxRX1nrEW0WMamZxA47Z3VUei6gr3uVI
ZiiGZFdm/8QuR7cthZpjdFBfRAWWDyxbAvQ3d6NlnOuXW9Q66LjP4jpRj3lH8nvE
fHHBaN/KWXuvQdps9BtuGlm+GhDCIshDehcD+am7I0rftH+Cza6W+C2sHK9xa5W0
DT4WeA73pjCCTx7Eyk/5AxyuPO4bL/b0uMFJMVon3ZOteT1k2WYemd3X8w6z7WyO
/SrtzJNoSqwetSKiGYIrmFAUVsnjrIcwvcgaodc1C5eaiu+dXOBWmV8AEQEAAYkC
NgQYAQoAIBYhBKBFYAUt4KeXx+6lUakNPYEtT6FCBQJejxeJAhsMAAoJEKkNPYEt
T6FCyNMP/1kcJMDVVnM9zBN9ejJx2/It1X6TzQp290TsARmnp9xqY9yuRgBwhOtZ
4aTBtFYzs0UJFo4LR8VnHieW2GAafQImMwSd+Hy5f1L0mz2YpR+xHEjXoyhHvPD9
Mmp6WG+vn3mw1tfsTgXItShykeEpBcObYrUjaW4IpmT+WPMMj/h74IHY5KM4x+6W
uBmUexzkTtimArNj4b+/3CAXzY04wZz7scb3/K7p6kcAmuOfRMcjnYFIxPyJ7ibW
3RWiWUKggmUCmtYRdy+d1lJVkezMhDl3+/z44GbPmdlg6EydcZXsHFoXfkev0cPv
IuweRv1gQ6uqAIcIk7rByWSYtOkdFfCb1U3zTd1rX3CKjd0d0GiZ/qxQISns0djI
Yp/6mhS+FSxXENoAfIHiUYZU3gEDTPgINceIkoj7pZFuyYRUaCAsuXi1l5WwMjdR
NamjBbUNSjjttxkgDeKbXQWPBvhorVG30Og0n2wxScMQ9qPydWukQ5EoMkR6L3SR
lXGr3SJveVBMr4MkHBKenJTsRRmAhMs7okQM9QpcV/JDcn9ZsiIdWBK/r9dhW7Yx
H9Q8jnaGO4Bg9dkXcd9fYbiX2GxUA8kW/97WkY5KmFqkGxAF5dLIsZx0tveyw+C/
djK2x8AoVgqj2QtggY8bU94Zfkr52yXHiR3GLYXb8KQUFuABEOCr
=6fSq
-----END PGP PUBLIC KEY BLOCK-----
```

**Comment by jwkaltz** [comment]
OK like this @sbrunner ?

**Review by sbrunner — APPROVED** [review]

**Pull request merged**
