### PR TITLE
Enable TinyOWS proxy and support datepicker in demo

### PR DESCRIPTION
**Pull request by tsauerwein**
See https://github.com/camptocamp/c2cgeoportal/pull/1327 and https://github.com/camptocamp/c2cgeoportal/pull/1340

### CODE REVIEW

**Comment by tsauerwein** [comment]
I updated the PR to also include the changes required for the datepicker (https://github.com/camptocamp/c2cgeoportal/pull/1340).

**Comment by asaunier** [comment]
Looks good to me

**Comment by sbrunner** [comment]
up ...

**Comment by tsauerwein** [comment]
Rebased. Please merge yourself when you need it.

**Comment by sbrunner** [comment]
Thanks @tsauerwein

**Pull request merged**
